/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project1_GUI;


import Project.*;
/**
 *
 * @author MBR
 */
public class Add_Student extends javax.swing.JFrame {

    /**
     * Creates new form Add_Student
     */
    public Add_Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UpdateDeleteStudentButton_FromStudents = new java.awt.Button();
        ListStudentsButton_FromStudents = new java.awt.Button();
        AddStudentButton_FromStudents = new java.awt.Button();
        Gender = new javax.swing.ButtonGroup();
        Level = new javax.swing.ButtonGroup();
        Group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelFirst = new java.awt.Label();
        jLabelPhone = new java.awt.Label();
        jLabelLast = new java.awt.Label();
        jLabelGender = new java.awt.Label();
        jLabelEmail = new java.awt.Label();
        jLabelGroup = new java.awt.Label();
        jLabelCourse1 = new java.awt.Label();
        jLabelCourse2 = new java.awt.Label();
        jTextFieldFirst = new javax.swing.JTextField();
        jTextFieldLast = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldGpa = new javax.swing.JTextField();
        jTextFieldCourse1 = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelLevel = new java.awt.Label();
        jLabelGpa = new java.awt.Label();
        jTextFieldCourse2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabelCourse3 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldCourse3 = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Level1 = new javax.swing.JRadioButton();
        Level2 = new javax.swing.JRadioButton();
        Level3 = new javax.swing.JRadioButton();
        Level4 = new javax.swing.JRadioButton();
        groupA = new javax.swing.JRadioButton();
        groupB = new javax.swing.JRadioButton();
        groupC = new javax.swing.JRadioButton();

        jPanel3.setBackground(new java.awt.Color(85, 65, 118));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home/Student");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manage Students");

        UpdateDeleteStudentButton_FromStudents.setBackground(new java.awt.Color(54, 32, 89));
        UpdateDeleteStudentButton_FromStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateDeleteStudentButton_FromStudents.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        UpdateDeleteStudentButton_FromStudents.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDeleteStudentButton_FromStudents.setLabel("Update / Delete student");
        UpdateDeleteStudentButton_FromStudents.setName(""); // NOI18N
        UpdateDeleteStudentButton_FromStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleteStudentButton_FromStudentsActionPerformed(evt);
            }
        });

        ListStudentsButton_FromStudents.setBackground(new java.awt.Color(54, 32, 89));
        ListStudentsButton_FromStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListStudentsButton_FromStudents.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        ListStudentsButton_FromStudents.setForeground(new java.awt.Color(255, 255, 255));
        ListStudentsButton_FromStudents.setLabel("List Students");
        ListStudentsButton_FromStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListStudentsButton_FromStudentsActionPerformed(evt);
            }
        });

        AddStudentButton_FromStudents.setBackground(new java.awt.Color(54, 32, 89));
        AddStudentButton_FromStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddStudentButton_FromStudents.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        AddStudentButton_FromStudents.setForeground(new java.awt.Color(255, 255, 255));
        AddStudentButton_FromStudents.setLabel("Add Student");
        AddStudentButton_FromStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentButton_FromStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addGap(727, 727, 727))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListStudentsButton_FromStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddStudentButton_FromStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateDeleteStudentButton_FromStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(385, 385, 385))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(AddStudentButton_FromStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ListStudentsButton_FromStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(UpdateDeleteStudentButton_FromStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        sidepane.setBackground(new java.awt.Color(54, 32, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 250, 30));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add Studet");
        sidepane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 230, 70));

        jButton4.setBackground(new java.awt.Color(54, 32, 89));
        jButton4.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Go Back");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        sidepane.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 340, 50));

        jButton5.setBackground(new java.awt.Color(54, 32, 89));
        jButton5.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Log Out");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        sidepane.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 340, 50));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));

        jLabelFirst.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelFirst.setText("First Name");

        jLabelPhone.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelPhone.setText("Phone");

        jLabelLast.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelLast.setText("Last Name");

        jLabelGender.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelGender.setText("Gender");

        jLabelEmail.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelGroup.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelGroup.setText("Group");

        jLabelCourse1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelCourse1.setText("Course 1");

        jLabelCourse2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelCourse2.setText("Course 2");

        jTextFieldGpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGpaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabelLevel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelLevel.setText("Level");

        jLabelGpa.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelGpa.setText("GPA");

        jButton6.setBackground(new java.awt.Color(54, 32, 89));
        jButton6.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Save");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabelCourse3.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelCourse3.setText("Course 3");

        jLabelId.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelId.setText("ID");

        jTextFieldCourse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourse3ActionPerformed(evt);
            }
        });

        Message.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Male.setBackground(new java.awt.Color(85, 65, 118));
        Gender.add(Male);
        Male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Female.setBackground(new java.awt.Color(85, 65, 118));
        Gender.add(Female);
        Female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Female.setText("Female");

        Level1.setBackground(new java.awt.Color(85, 65, 118));
        Level.add(Level1);
        Level1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level1.setText("1");
        Level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level1ActionPerformed(evt);
            }
        });

        Level2.setBackground(new java.awt.Color(85, 65, 118));
        Level.add(Level2);
        Level2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level2.setText("2");

        Level3.setBackground(new java.awt.Color(85, 65, 118));
        Level.add(Level3);
        Level3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level3.setText("3");

        Level4.setBackground(new java.awt.Color(85, 65, 118));
        Level.add(Level4);
        Level4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level4.setText("4");

        groupA.setBackground(new java.awt.Color(85, 65, 118));
        Group.add(groupA);
        groupA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        groupA.setText("A");

        groupB.setBackground(new java.awt.Color(85, 65, 118));
        Group.add(groupB);
        groupB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        groupB.setText("B");

        groupC.setBackground(new java.awt.Color(85, 65, 118));
        Group.add(groupC);
        groupC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        groupC.setText("C");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(31, 31, 31))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLast, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldCourse3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(jTextFieldCourse2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(jTextFieldFirst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Male)
                                .addGap(128, 128, 128)
                                .addComponent(Female))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(groupA)
                                .addGap(36, 36, 36)
                                .addComponent(groupB)
                                .addGap(36, 36, 36)
                                .addComponent(groupC)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Level1)
                        .addGap(18, 18, 18)
                        .addComponent(Level2)
                        .addGap(29, 29, 29)
                        .addComponent(Level3)
                        .addGap(31, 31, 31)
                        .addComponent(Level4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLast, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Male)
                                .addComponent(Female)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Level1)
                                        .addComponent(Level2)
                                        .addComponent(Level3)
                                        .addComponent(Level4))
                                    .addComponent(jLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jTextFieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(groupA)
                        .addComponent(groupB)
                        .addComponent(groupC)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCourse1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCourse1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGpaActionPerformed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        // this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MousePressed

    private void UpdateDeleteStudentButton_FromStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleteStudentButton_FromStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateDeleteStudentButton_FromStudentsActionPerformed

    private void ListStudentsButton_FromStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListStudentsButton_FromStudentsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new List_Lecturer().setVisible(true);
    }//GEN-LAST:event_ListStudentsButton_FromStudentsActionPerformed

    private void AddStudentButton_FromStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButton_FromStudentsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Add_Student().setVisible(true);
    }//GEN-LAST:event_AddStudentButton_FromStudentsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Student().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login_form().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (    !jTextFieldId.getText().equals("")      &&
                !jTextFieldFirst.getText().equals("")   &&
                !jTextFieldLast.getText().equals("")    &&
                !jTextFieldPhone.getText().equals("")   &&
                !jTextFieldEmail.getText().equals("")   &&
                (Male.isSelected() || Female.isSelected())  &&
                (Level1.isSelected() || Level2.isSelected() || Level3.isSelected() || Level4.isSelected() )   &&
                !jTextFieldGpa.getText().equals("")     &&
                (groupA.isSelected() || groupB.isSelected() || groupC.isSelected() )   &&
                !jTextFieldCourse1.getText().equals("") &&
                !jTextFieldCourse2.getText().equals("") &&
                !jTextFieldCourse3.getText().equals("")     ){
            
            
              Project.Student x = new Project.Student();
              
              x.setId(Integer.parseInt(jTextFieldId.getText()));
              x.setFirstName(jTextFieldFirst.getText());
              x.setLastName(jTextFieldLast.getText());
              x.setPhone(jTextFieldPhone.getText());
              x.setEmail(jTextFieldEmail.getText());
              if (Male.isSelected())
                x.setGender(Male.getText());
              if (Female.isSelected())
                x.setGender(Female.getText());                         
              if (Level1.isSelected())
                x.setLevel(Integer.parseInt(Level1.getText()));
              if (Level2.isSelected())
                x.setLevel(Integer.parseInt(Level2.getText()));              
              if (Level3.isSelected())
                x.setLevel(Integer.parseInt(Level3.getText()));              
              if (Level4.isSelected())
                x.setLevel(Integer.parseInt(Level4.getText()));              
              x.setGpa(Double.parseDouble(jTextFieldGpa.getText()));
              if (groupA.isSelected())
                x.setGroup(groupA.getText()); 
              if (groupB.isSelected())
                x.setGroup(groupB.getText());              
              if (groupC.isSelected())
                x.setGroup(groupC.getText());             
              x.setCourse1(jTextFieldCourse1.getText());
              x.setCourse2(jTextFieldCourse2.getText());
              x.setCourse3(jTextFieldCourse3.getText());
              
              if (x.addStudent()){
                  Message.setText("Done");
                  resetPanelData();
              }
              else {
                  Message.setText("Failed");
              }
        }
        else {
               Message.setText("Please Fill Fields");
       
    }         
    }//GEN-LAST:event_jButton6ActionPerformed
 
        private void resetPanelData() { 
        
            jTextFieldId.setText("");
            jTextFieldFirst.setText("");
            jTextFieldLast.setText("");
            jTextFieldPhone.setText("");
            jTextFieldEmail.setText("");
            Gender.clearSelection();
            Level.clearSelection();
            jTextFieldGpa.setText("");
            Group.clearSelection();
            jTextFieldCourse1.setText("");
            jTextFieldCourse2.setText("");
            jTextFieldCourse3.setText("");
            
         }
    
   
    
    private void jTextFieldCourse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourse3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourse3ActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void Level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Level1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button AddStudentButton_FromStudents;
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup Gender;
    private javax.swing.ButtonGroup Group;
    private javax.swing.ButtonGroup Level;
    private javax.swing.JRadioButton Level1;
    private javax.swing.JRadioButton Level2;
    private javax.swing.JRadioButton Level3;
    private javax.swing.JRadioButton Level4;
    private java.awt.Button ListStudentsButton_FromStudents;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel Message;
    private java.awt.Button UpdateDeleteStudentButton_FromStudents;
    private javax.swing.JRadioButton groupA;
    private javax.swing.JRadioButton groupB;
    private javax.swing.JRadioButton groupC;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private java.awt.Label jLabelCourse1;
    private java.awt.Label jLabelCourse2;
    private javax.swing.JLabel jLabelCourse3;
    private java.awt.Label jLabelEmail;
    private java.awt.Label jLabelFirst;
    private java.awt.Label jLabelGender;
    private java.awt.Label jLabelGpa;
    private java.awt.Label jLabelGroup;
    private javax.swing.JLabel jLabelId;
    private java.awt.Label jLabelLast;
    private java.awt.Label jLabelLevel;
    private java.awt.Label jLabelPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCourse1;
    private javax.swing.JTextField jTextFieldCourse2;
    private javax.swing.JTextField jTextFieldCourse3;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirst;
    private javax.swing.JTextField jTextFieldGpa;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLast;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
