/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1_GUI;

/**
 *
 * @author MBR
 */
import java.awt.*;
import javax.swing.*;

public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Home1
     */
    public Admin() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GoBackButton_Admin = new java.awt.Button();
        StudentsButton_Admin = new java.awt.Button();
        LecturerButton_Admin = new java.awt.Button();
        UpdateInfoButton_Admin1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bgFocusLost(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 32, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 240, 30));

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Admin");
        sidepane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, 70));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 740));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 40, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("College Examination Manage System");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 300, 40));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));
        jPanel2.setFont(new java.awt.Font("Algerian", 0, 13)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome To The College System");

        GoBackButton_Admin.setBackground(new java.awt.Color(54, 32, 89));
        GoBackButton_Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoBackButton_Admin.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        GoBackButton_Admin.setForeground(new java.awt.Color(255, 255, 255));
        GoBackButton_Admin.setLabel("Log Out");
        GoBackButton_Admin.setName(""); // NOI18N
        GoBackButton_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButton_AdminActionPerformed(evt);
            }
        });

        StudentsButton_Admin.setBackground(new java.awt.Color(54, 32, 89));
        StudentsButton_Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentsButton_Admin.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        StudentsButton_Admin.setForeground(new java.awt.Color(255, 255, 255));
        StudentsButton_Admin.setLabel("Students");
        StudentsButton_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsButton_AdminActionPerformed(evt);
            }
        });

        LecturerButton_Admin.setBackground(new java.awt.Color(54, 32, 89));
        LecturerButton_Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LecturerButton_Admin.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        LecturerButton_Admin.setForeground(new java.awt.Color(255, 255, 255));
        LecturerButton_Admin.setLabel("Lecturers");
        LecturerButton_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecturerButton_AdminActionPerformed(evt);
            }
        });

        UpdateInfoButton_Admin1.setActionCommand("Update_AdminInfo");
        UpdateInfoButton_Admin1.setBackground(new java.awt.Color(54, 32, 89));
        UpdateInfoButton_Admin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateInfoButton_Admin1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        UpdateInfoButton_Admin1.setForeground(new java.awt.Color(255, 255, 255));
        UpdateInfoButton_Admin1.setLabel("Update Information");
        UpdateInfoButton_Admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoButton_Admin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GoBackButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LecturerButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentsButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateInfoButton_Admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(LecturerButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(StudentsButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(UpdateInfoButton_Admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(GoBackButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        UpdateInfoButton_Admin1.getAccessibleContext().setAccessibleName("Update_AdminInfo");

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 970, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
       // this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void bgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bgFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bgFocusLost

    private void StudentsButton_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsButton_AdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Student().setVisible(true);
    }//GEN-LAST:event_StudentsButton_AdminActionPerformed

    private void LecturerButton_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecturerButton_AdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Lecturer1().setVisible(true);
    }//GEN-LAST:event_LecturerButton_AdminActionPerformed

    private void UpdateInfoButton_Admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoButton_Admin1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Update_Admin_info().setVisible(true);
    }//GEN-LAST:event_UpdateInfoButton_Admin1ActionPerformed

    private void GoBackButton_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButton_AdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login_form().setVisible(true);
    }//GEN-LAST:event_GoBackButton_AdminActionPerformed
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button GoBackButton_Admin;
    private java.awt.Button LecturerButton_Admin;
    private java.awt.Button StudentsButton_Admin;
    private java.awt.Button UpdateInfoButton_Admin1;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
