/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project1_GUI;

/**
 *
 * @author Nada Hassan
 */
public class UpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePanel
     */
    public UpdatePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Answers = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Question = new javax.swing.JLabel();
        jLabela1 = new javax.swing.JLabel();
        jLabelCorrect = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jTextFieldQuestion = new javax.swing.JTextField();
        jTextFielda1 = new javax.swing.JTextField();
        jTextFielda2 = new javax.swing.JTextField();
        jTextFielda3 = new javax.swing.JTextField();
        jTextFieldQNumber2 = new javax.swing.JTextField();
        jLabela2 = new javax.swing.JLabel();
        jLabela3 = new javax.swing.JLabel();
        jLabela4 = new javax.swing.JLabel();
        jTextFielda4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextFieldQNumber = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        A = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(85, 65, 118));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));

        Question.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        Question.setForeground(new java.awt.Color(255, 255, 255));
        Question.setText("Question");

        jLabela1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabela1.setForeground(new java.awt.Color(255, 255, 255));
        jLabela1.setText("A");

        jLabelCorrect.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabelCorrect.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorrect.setText("Correct Answer:");

        saveButton.setBackground(new java.awt.Color(54, 32, 89));
        saveButton.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Delete");
        saveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveButton.setFocusPainted(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jTextFielda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielda1ActionPerformed(evt);
            }
        });

        jTextFielda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielda2ActionPerformed(evt);
            }
        });

        jTextFielda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielda3ActionPerformed(evt);
            }
        });

        jTextFieldQNumber2.setEditable(false);

        jLabela2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabela2.setForeground(new java.awt.Color(255, 255, 255));
        jLabela2.setText("B");

        jLabela3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabela3.setForeground(new java.awt.Color(255, 255, 255));
        jLabela3.setText("C");

        jLabela4.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabela4.setForeground(new java.awt.Color(255, 255, 255));
        jLabela4.setText("D");

        jTextFielda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielda4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(54, 32, 89));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(54, 32, 89));
        jButton2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Message.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        C.setBackground(new java.awt.Color(85, 65, 118));
        Answers.add(C);
        C.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        C.setText("C");

        D.setBackground(new java.awt.Color(85, 65, 118));
        Answers.add(D);
        D.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        D.setText("D");

        B.setBackground(new java.awt.Color(85, 65, 118));
        Answers.add(B);
        B.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B.setText("B");

        A.setBackground(new java.awt.Color(85, 65, 118));
        Answers.add(A);
        A.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        A.setText("A");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabela1)
                            .addComponent(jLabela3)
                            .addComponent(jLabela4)
                            .addComponent(jLabela2))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFielda1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                            .addComponent(jTextFielda2)
                            .addComponent(jTextFielda3)
                            .addComponent(jTextFielda4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A)
                                .addGap(45, 45, 45)
                                .addComponent(B)
                                .addGap(53, 53, 53)
                                .addComponent(C)
                                .addGap(36, 36, 36)
                                .addComponent(D))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldQNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldQNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jTextFieldQNumber)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabela1)
                    .addComponent(jTextFielda1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabela2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFielda2))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFielda3)
                    .addComponent(jLabela3))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabela4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFielda4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A)
                        .addComponent(B)
                        .addComponent(C)
                        .addComponent(D)))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
        );

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldQNumber.getText().equals("")){
            
            Project.Exam x =new Project.Exam();
            
            if (x.deleteExam(Integer.parseInt(jTextFieldQNumber.getText()))){
                Message.setText("Deleted");
                resetPanelData();
                
            }
            else {
                Message.setText("Failed");
                
            }
        }
        else {
            Message.setText("Enter ID");
                
        }    
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jTextFielda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielda1ActionPerformed

    private void jTextFielda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielda2ActionPerformed

    private void jTextFielda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielda3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielda3ActionPerformed

    private void jTextFielda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielda4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielda4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (    !jTextFieldQNumber2.getText().equals("")      &&
                !jTextFieldQuestion.getText().equals("")     &&
                !jTextFielda1.getText().equals("")           &&
                !jTextFielda2.getText().equals("")           &&
                !jTextFielda3.getText().equals("")           &&
                !jTextFielda4.getText().equals("")           &&
                (A.isSelected() || B.isSelected() || C.isSelected() || D.isSelected() )   ){
            
            
            
              Project.Exam x = new Project.Exam();
              
              x.setQNumber(Integer.parseInt(jTextFieldQNumber2.getText()));
              x.setQuestion(jTextFieldQuestion.getText());
              x.setA1(jTextFielda1.getText());
              x.setA2(jTextFielda2.getText());
              x.setA3(jTextFielda3.getText());
              x.setA4(jTextFielda4.getText());
              if (A.isSelected())
                x.setCorrect("A"); 
              if (B.isSelected())
                x.setCorrect("B");              
              if (C.isSelected())
                x.setCorrect("C"); 
              if (D.isSelected())
                x.setCorrect("D");
              
              if (x.updateExam()){
                  Message.setText("Done");
                  resetPanelData();
              }
              else {
                  Message.setText("Failed");
              }
        }
        else {
               Message.setText("Please Fill Fields");
        
             }             
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldQNumber.getText().equals("")){
            Project.Exam x =new Project.Exam();
            Project.Exam returned = x.searchExamById(Integer.parseInt(jTextFieldQNumber.getText()));
            if (returned.getQNumber() > 0 ){
                setPanelData(returned);
            }
            else {
                Message.setText("Not Found");
            }
       
        }
        else {
            Message.setText("Please Enter ID");
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed



    protected void setPanelData(Project.Exam x){
        jTextFieldQNumber2.setText("" + x.getQNumber());
        jTextFieldQuestion.setText("" + x.getQuestion());
        jTextFielda1.setText("" + x.getA1());
        jTextFielda2.setText("" + x.getA2());
        jTextFielda3.setText("" + x.getA3());
        jTextFielda4.setText("" + x.getA4());
              if (x.getCorrect().equals("A"))
                A.setSelected(true);
              if (x.getCorrect().equals("B"))
                B.setSelected(true);  
              if (x.getCorrect().equals("C"))
                C.setSelected(true);
              if (x.getCorrect().equals("D"))
                D.setSelected(true);        
    }
    
    
    
    protected void resetPanelData() { 
        
            jTextFieldQNumber.setText("");
            jTextFieldQNumber2.setText("");
            jTextFieldQuestion.setText("");
            jTextFielda1.setText("");
            jTextFielda2.setText("");
            jTextFielda3.setText("");
            jTextFielda4.setText("");
            Answers.clearSelection();
            

         }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.ButtonGroup Answers;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel Question;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCorrect;
    private javax.swing.JLabel jLabela1;
    private javax.swing.JLabel jLabela2;
    private javax.swing.JLabel jLabela3;
    private javax.swing.JLabel jLabela4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldQNumber;
    private javax.swing.JTextField jTextFieldQNumber2;
    private javax.swing.JTextField jTextFieldQuestion;
    private javax.swing.JTextField jTextFielda1;
    private javax.swing.JTextField jTextFielda2;
    private javax.swing.JTextField jTextFielda3;
    private javax.swing.JTextField jTextFielda4;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
