/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1_GUI;

import Project.*;
/**
 *
 * @author MBR
 */
public class Update_Lecturer extends javax.swing.JFrame {

    /**
     * Creates new form Update_Students
     */
    public Update_Lecturer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        sidepane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        GoBackButton_fromListStu = new java.awt.Button();
        button3 = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabelId = new java.awt.Label();
        jLabelLast = new java.awt.Label();
        jLabelFirst = new java.awt.Label();
        jLabelEmail = new java.awt.Label();
        jLabelPhone = new java.awt.Label();
        jLabelGender = new java.awt.Label();
        jLabelCourse = new java.awt.Label();
        jTextFieldId2 = new javax.swing.JTextField();
        jTextFieldFirst = new javax.swing.JTextField();
        jTextFieldLast = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jTextFieldId = new javax.swing.JTextField();
        LecturerButton_Admin = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCourse = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        sidepane.setBackground(new java.awt.Color(54, 32, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 280, 30));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Update / Delete Lecturer");
        sidepane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 290, 70));

        GoBackButton_fromListStu.setBackground(new java.awt.Color(54, 32, 89));
        GoBackButton_fromListStu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoBackButton_fromListStu.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        GoBackButton_fromListStu.setForeground(new java.awt.Color(255, 255, 255));
        GoBackButton_fromListStu.setLabel("Go Back");
        GoBackButton_fromListStu.setName(""); // NOI18N
        GoBackButton_fromListStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButton_fromListStuActionPerformed(evt);
            }
        });
        sidepane.add(GoBackButton_fromListStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 340, 50));

        button3.setBackground(new java.awt.Color(54, 32, 89));
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button3.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setLabel("  Log out  ");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        sidepane.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 340, 50));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));
        jPanel2.setPreferredSize(new java.awt.Dimension(1112, 768));

        jLabelId.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelId.setText("ID");

        jLabelLast.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelLast.setText("Last Name");

        jLabelFirst.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelFirst.setText("First Name");

        jLabelEmail.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelPhone.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelPhone.setText("Phone");

        jLabelGender.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelGender.setName(""); // NOI18N
        jLabelGender.setText("Gender");

        jLabelCourse.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelCourse.setText("Course");

        jTextFieldId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldId2ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(54, 32, 89));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Update");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(54, 32, 89));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button2.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("Delete");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        LecturerButton_Admin.setBackground(new java.awt.Color(54, 32, 89));
        LecturerButton_Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LecturerButton_Admin.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        LecturerButton_Admin.setForeground(new java.awt.Color(255, 255, 255));
        LecturerButton_Admin.setLabel("Search");
        LecturerButton_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecturerButton_AdminActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("  X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Message.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Female.setBackground(new java.awt.Color(85, 65, 118));
        Gender.add(Female);
        Female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Female.setText("Female");

        Male.setBackground(new java.awt.Color(85, 65, 118));
        Gender.add(Male);
        Male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(41, 41, 41)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(jTextFieldId2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(jTextFieldLast, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(jTextFieldFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(jTextFieldCourse)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Male)
                                    .addGap(128, 128, 128)
                                    .addComponent(Female))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(LecturerButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 173, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LecturerButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldId2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLast, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Male)
                        .addComponent(Female)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LecturerButton_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecturerButton_AdminActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldId.getText().equals("")){
            Project.Doctor x =new Project.Doctor();
            Project.Doctor returned = x.searchDoctorById(Integer.parseInt(jTextFieldId.getText()));
            if (returned.getId() > 0 ){
                setPanelData(returned);
            }
            else {
                Message.setText("Not Found");
            }
       
        }
        else {
            Message.setText("Please Enter ID");
        }
                
        
    }//GEN-LAST:event_LecturerButton_AdminActionPerformed

    private void GoBackButton_fromListStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButton_fromListStuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Lecturer1().setVisible(true);
    }//GEN-LAST:event_GoBackButton_fromListStuActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldId.getText().equals("")){
            
            Project.Doctor x =new Project.Doctor();
            
            if (x.deleteDoctor(Integer.parseInt(jTextFieldId.getText()))){
                Message.setText("Deleted");
                resetPanelData();
                
            }
            else {
                Message.setText("Failed");
                
            }
        }
        else {
            Message.setText("Enter ID");
                
        }        
        
    }//GEN-LAST:event_button2ActionPerformed

    private void jTextFieldId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldId2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login_form().setVisible(true);
    }//GEN-LAST:event_button3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (    !jTextFieldId2.getText().equals("")      &&
                !jTextFieldFirst.getText().equals("")   &&
                !jTextFieldLast.getText().equals("")    &&
                !jTextFieldPhone.getText().equals("")   &&
                !jTextFieldEmail.getText().equals("")   &&
                (Male.isSelected() || Female.isSelected())  &&
                !jTextFieldCourse.getText().equals("")     ){
            
            
            
              Project.Doctor x = new Project.Doctor();
              
              x.setId(Integer.parseInt(jTextFieldId2.getText()));
              x.setFirstName(jTextFieldFirst.getText());
              x.setLastName(jTextFieldLast.getText());
              x.setPhone(jTextFieldPhone.getText());
              x.setEmail(jTextFieldEmail.getText());
              if (Male.isSelected())
                x.setGender(Male.getText());
              if (Female.isSelected())
                x.setGender(Female.getText()); 
              x.setCourse(jTextFieldCourse.getText());
              
              if (x.updateDoctor()){
                  Message.setText("Done");
                  resetPanelData();
              }
              else {
                  Message.setText("Failed");
              }
        }
        else {
               Message.setText("Please Fill Fields");
        
             }        
        
    }//GEN-LAST:event_button1ActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Lecturer().setVisible(true);
            }
        });
    }
    
    protected void setPanelData(Project.Doctor x){
        jTextFieldId2.setText("" + x.getId());
        jTextFieldFirst.setText("" + x.getFirstName());
        jTextFieldLast.setText("" + x.getLastName());
        jTextFieldPhone.setText("" + x.getPhone());
        jTextFieldEmail.setText("" + x.getEmail());
              if (x.getGender().equals("Male"))
                 Male.setSelected(true);
              if (x.getGender().equals("Female"))
                 Female.setSelected(true);      
        jTextFieldCourse.setText("" + x.getCourse());
        
    }
    
    
    
    protected void resetPanelData() { 
        
            jTextFieldId.setText("");
            jTextFieldId2.setText("");
            jTextFieldFirst.setText("");
            jTextFieldLast.setText("");
            jTextFieldPhone.setText("");
            jTextFieldEmail.setText("");
            Gender.clearSelection();
            jTextFieldCourse.setText("");

         }    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup Gender;
    private java.awt.Button GoBackButton_fromListStu;
    private java.awt.Button LecturerButton_Admin;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel Message;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private java.awt.Label jLabelCourse;
    private java.awt.Label jLabelEmail;
    private java.awt.Label jLabelFirst;
    private java.awt.Label jLabelGender;
    private java.awt.Label jLabelId;
    private java.awt.Label jLabelLast;
    private java.awt.Label jLabelPhone;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCourse;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirst;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldId2;
    private javax.swing.JTextField jTextFieldLast;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
