/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1_GUI;

/**
 *
 * @author MBR
 */
public class Update_Stud_info extends javax.swing.JFrame {

    /**
     * Creates new form Update_Stud_info
     */
    public Update_Stud_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        Level = new javax.swing.ButtonGroup();
        Group = new javax.swing.ButtonGroup();
        sidepane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        IDlabel1_AddStu_fromStudent = new java.awt.Label();
        LNamelabel1_AddStu_fromStudent = new java.awt.Label();
        FNamelabel1_AddStu_fromStudent = new java.awt.Label();
        Passlabel1_AddStu_fromStudent = new java.awt.Label();
        EmailLabel1_AddStu_fromStudent = new java.awt.Label();
        RePasslabel1_AddStu_fromStudent = new java.awt.Label();
        Agelabel1_AddStu_fromStudent = new java.awt.Label();
        GPAlabel1_AddStu_fromStudent = new java.awt.Label();
        jTextFieldId2 = new javax.swing.JTextField();
        jTextFieldFirst = new javax.swing.JTextField();
        jTextFieldLast = new javax.swing.JTextField();
        jTextFieldCourse1 = new javax.swing.JTextField();
        jTextFieldCourse3 = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        Levellabel1_AddStu_fromStudent1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        Departmentlabel1_AddStu_fromStudent = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldCourse2 = new javax.swing.JTextField();
        jTextFieldGpa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        Level2 = new javax.swing.JRadioButton();
        Level3 = new javax.swing.JRadioButton();
        Level4 = new javax.swing.JRadioButton();
        Level1 = new javax.swing.JRadioButton();
        groupA = new javax.swing.JRadioButton();
        groupC = new javax.swing.JRadioButton();
        groupB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        sidepane.setBackground(new java.awt.Color(54, 32, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 280, 30));

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Update student");
        sidepane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 290, 70));

        jButton4.setBackground(new java.awt.Color(54, 32, 89));
        jButton4.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Log Out");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        sidepane.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 340, 50));

        jButton5.setBackground(new java.awt.Color(54, 32, 89));
        jButton5.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Go Back");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        sidepane.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 340, 50));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));

        IDlabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        IDlabel1_AddStu_fromStudent.setText("ID");

        LNamelabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        LNamelabel1_AddStu_fromStudent.setText("Last Name");

        FNamelabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        FNamelabel1_AddStu_fromStudent.setText("First Name");

        Passlabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        Passlabel1_AddStu_fromStudent.setText("Phone");

        EmailLabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        EmailLabel1_AddStu_fromStudent.setText("Email");

        RePasslabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        RePasslabel1_AddStu_fromStudent.setText("Gender");

        Agelabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        Agelabel1_AddStu_fromStudent.setText("Level");

        GPAlabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        GPAlabel1_AddStu_fromStudent.setText("Group");

        jTextFieldId2.setEditable(false);

        jTextFieldCourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourse1ActionPerformed(evt);
            }
        });

        Levellabel1_AddStu_fromStudent1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        Levellabel1_AddStu_fromStudent1.setText("GPA");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        Departmentlabel1_AddStu_fromStudent.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        Departmentlabel1_AddStu_fromStudent.setText("Course 1");

        jButton6.setBackground(new java.awt.Color(54, 32, 89));
        jButton6.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Update");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(54, 32, 89));
        jButton7.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Search");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel1.setText("Course 2");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("Course 3");

        Message.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton9.setBackground(new java.awt.Color(54, 32, 89));
        jButton9.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Delete");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        Female.setBackground(new java.awt.Color(85, 65, 118));
        Gender.add(Female);
        Female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Female.setText("Female");

        Male.setBackground(new java.awt.Color(85, 65, 118));
        Gender.add(Male);
        Male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Level2.setBackground(new java.awt.Color(85, 65, 118));
        Level.add(Level2);
        Level2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level2.setText("2");

        Level3.setBackground(new java.awt.Color(85, 65, 118));
        Level.add(Level3);
        Level3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level3.setText("3");

        Level4.setBackground(new java.awt.Color(85, 65, 118));
        Level.add(Level4);
        Level4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level4.setText("4");

        Level1.setBackground(new java.awt.Color(85, 65, 118));
        Level.add(Level1);
        Level1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level1.setText("1");
        Level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level1ActionPerformed(evt);
            }
        });

        groupA.setBackground(new java.awt.Color(85, 65, 118));
        Group.add(groupA);
        groupA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        groupA.setText("A");

        groupC.setBackground(new java.awt.Color(85, 65, 118));
        Group.add(groupC);
        groupC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        groupC.setText("C");

        groupB.setBackground(new java.awt.Color(85, 65, 118));
        Group.add(groupB);
        groupB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        groupB.setText("B");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IDlabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FNamelabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LNamelabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailLabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Passlabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Agelabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RePasslabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldId2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLast, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Male)
                                        .addGap(107, 107, 107)
                                        .addComponent(Female))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Level1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Level2)
                                        .addGap(29, 29, 29)
                                        .addComponent(Level3)
                                        .addGap(31, 31, 31)
                                        .addComponent(Level4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Levellabel1_AddStu_fromStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(GPAlabel1_AddStu_fromStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(Departmentlabel1_AddStu_fromStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(groupA)
                                        .addGap(36, 36, 36)
                                        .addComponent(groupB)
                                        .addGap(36, 36, 36)
                                        .addComponent(groupC)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jTextFieldId))))
                .addGap(4, 4, 4)
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldId2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDlabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FNamelabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LNamelabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLast, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Passlabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmailLabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Male)
                                .addComponent(Female))
                            .addComponent(RePasslabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Level1)
                                    .addComponent(Level2)
                                    .addComponent(Level3)
                                    .addComponent(Level4))
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Agelabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Levellabel1_AddStu_fromStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(GPAlabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(groupA)
                            .addComponent(groupB)
                            .addComponent(groupC))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Departmentlabel1_AddStu_fromStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jTextFieldCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
        new Login_form().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Student_base().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldCourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourse1ActionPerformed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        // this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (    !jTextFieldId2.getText().equals("")      &&
            !jTextFieldFirst.getText().equals("")   &&
            !jTextFieldLast.getText().equals("")    &&
            !jTextFieldPhone.getText().equals("")   &&
            !jTextFieldEmail.getText().equals("")   &&
            (Male.isSelected() || Female.isSelected())                                                    &&
            (Level1.isSelected() || Level2.isSelected() || Level3.isSelected() || Level4.isSelected() )   &&
            !jTextFieldGpa.getText().equals("")     &&
            (groupA.isSelected() || groupB.isSelected() || groupC.isSelected() )    &&
            !jTextFieldCourse1.getText().equals("") &&
            !jTextFieldCourse2.getText().equals("") &&
            !jTextFieldCourse3.getText().equals("")     ){

            Project.Student x = new Project.Student();

            x.setId(Integer.parseInt(jTextFieldId2.getText()));
            x.setFirstName(jTextFieldFirst.getText());
            x.setLastName(jTextFieldLast.getText());
            x.setPhone(jTextFieldPhone.getText());
            x.setEmail(jTextFieldEmail.getText());
              if (Male.isSelected())
                x.setGender(Male.getText());
              if (Female.isSelected())
                x.setGender(Female.getText());              
              
              if (Level1.isSelected())
                x.setLevel(Integer.parseInt(Level1.getText()));
              if (Level2.isSelected())
                x.setLevel(Integer.parseInt(Level2.getText()));              
              if (Level3.isSelected())
                x.setLevel(Integer.parseInt(Level3.getText()));              
              if (Level4.isSelected())
                x.setLevel(Integer.parseInt(Level4.getText()));  
            x.setGpa(Double.parseDouble(jTextFieldGpa.getText()));
              if (groupA.isSelected())
                x.setGroup(groupA.getText()); 
              if (groupB.isSelected())
                x.setGroup(groupB.getText());              
              if (groupC.isSelected())
                x.setGroup(groupC.getText());  
            x.setCourse1(jTextFieldCourse1.getText());
            x.setCourse2(jTextFieldCourse2.getText());
            x.setCourse3(jTextFieldCourse3.getText());

            if (x.updateStudent()){
                Message.setText("Done");
                resetPanelData();
            }
            else {
                Message.setText("Failed");
            }
        }
        else {
            Message.setText("Please Fill Fields");

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldId.getText().equals("")){
            Project.Student x =new Project.Student();
            Project.Student returned = x.searchStudentById(Integer.parseInt(jTextFieldId.getText()));
            if (returned.getId() > 0 ){
                setPanelData(returned);
            }
            else {
                Message.setText("Not Found");
            }

        }
        else {
            Message.setText("Please Enter ID");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldId.getText().equals("")){

            Project.Student x =new Project.Student();

            if (x.deleteStudent(Integer.parseInt(jTextFieldId.getText()))){
                Message.setText("Deleted");
                resetPanelData();

            }
            else {
                Message.setText("Failed");

            }
        }
        else {
            Message.setText("Enter ID");

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void Level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Level1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Stud_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Stud_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Stud_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Stud_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Stud_info().setVisible(true);
            }
        });
    }
    protected void setPanelData(Project.Student x){
        jTextFieldId2.setText("" + x.getId());
        jTextFieldFirst.setText("" + x.getFirstName());
        jTextFieldLast.setText("" + x.getLastName());
        jTextFieldPhone.setText("" + x.getPhone());
        jTextFieldEmail.setText("" + x.getEmail());
              if (x.getGender().equals("Male"))
                 Male.setSelected(true);
              if (x.getGender().equals("Female"))
                 Female.setSelected(true);        
              
              if (x.getLevel() == 1)
                Level1.setSelected(true);  
              if (x.getLevel() == 2)
                Level2.setSelected(true);               
              if (x.getLevel() == 3)
                Level3.setSelected(true);              
              if (x.getLevel() == 4)
                Level4.setSelected(true);          

        jTextFieldGpa.setText("" + x.getGpa());
              if (x.getGroup().equals("A"))
                groupA.setSelected(true);
              if (x.getGroup().equals("B"))
                groupB.setSelected(true);  
              if (x.getGroup().equals("C"))
                groupC.setSelected(true);
        jTextFieldCourse1.setText("" + x.getCourse1());
        jTextFieldCourse2.setText("" + x.getCourse2());
        jTextFieldCourse3.setText("" + x.getCourse3());

    }
    
    
    
    protected void resetPanelData() { 
        
            jTextFieldId.setText("");
            jTextFieldId2.setText("");
            jTextFieldFirst.setText("");
            jTextFieldLast.setText("");
            jTextFieldPhone.setText("");
            jTextFieldEmail.setText("");
            Gender.clearSelection();
            Level.clearSelection();
            jTextFieldGpa.setText("");
            Group.clearSelection();
            jTextFieldCourse1.setText("");
            jTextFieldCourse2.setText("");
            jTextFieldCourse3.setText("");

         }    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Agelabel1_AddStu_fromStudent;
    private java.awt.Label Departmentlabel1_AddStu_fromStudent;
    private java.awt.Label EmailLabel1_AddStu_fromStudent;
    private java.awt.Label FNamelabel1_AddStu_fromStudent;
    private javax.swing.JRadioButton Female;
    private java.awt.Label GPAlabel1_AddStu_fromStudent;
    private javax.swing.ButtonGroup Gender;
    private javax.swing.ButtonGroup Group;
    private java.awt.Label IDlabel1_AddStu_fromStudent;
    private java.awt.Label LNamelabel1_AddStu_fromStudent;
    private javax.swing.ButtonGroup Level;
    private javax.swing.JRadioButton Level1;
    private javax.swing.JRadioButton Level2;
    private javax.swing.JRadioButton Level3;
    private javax.swing.JRadioButton Level4;
    private java.awt.Label Levellabel1_AddStu_fromStudent1;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel Message;
    private java.awt.Label Passlabel1_AddStu_fromStudent;
    private java.awt.Label RePasslabel1_AddStu_fromStudent;
    private javax.swing.JRadioButton groupA;
    private javax.swing.JRadioButton groupB;
    private javax.swing.JRadioButton groupC;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCourse1;
    private javax.swing.JTextField jTextFieldCourse2;
    private javax.swing.JTextField jTextFieldCourse3;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirst;
    private javax.swing.JTextField jTextFieldGpa;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldId2;
    private javax.swing.JTextField jTextFieldLast;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
